image: node:10.4.1
variables:
  GIT_SUBMODULE_STRATEGY: recursive
pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install
  - hexo generate
  artifacts:
    paths:
    - public
  only:
  - master
